<?php

return [
    'schedule' => [
        'day_1' => [
            'meal_1' => null,
            'meal_2' => null,
            'meal_3' => null,
            'meal_4' => null,
            'meal_5' => null,
            'meal_6' => null,
        ],
        'day_2' => [
            'meal_1' => null,
            'meal_2' => null,
            'meal_3' => null,
            'meal_4' => null,
            'meal_5' => null,
            'meal_6' => null,
        ],
        'day_3' => [
            'meal_1' => null,
            'meal_2' => null,
            'meal_3' => null,
            'meal_4' => null,
            'meal_5' => null,
            'meal_6' => null,
        ],
        'day_4' => [
            'meal_1' => null,
            'meal_2' => null,
            'meal_3' => null,
            'meal_4' => null,
            'meal_5' => null,
            'meal_6' => null,
        ],
        'day_5' => [
            'meal_1' => null,
            'meal_2' => null,
            'meal_3' => null,
            'meal_4' => null,
            'meal_5' => null,
            'meal_6' => null,
        ],
        'day_6' => [
            'meal_1' => null,
            'meal_2' => null,
            'meal_3' => null,
            'meal_4' => null,
            'meal_5' => null,
            'meal_6' => null,
        ],
        'day_7' => [
            'meal_1' => null,
            'meal_2' => null,
            'meal_3' => null,
            'meal_4' => null,
            'meal_5' => null,
            'meal_6' => null,
        ],
    ],
    'leftovers' => [
        'day_1' => [
            'meal_1' => null,
            'meal_2' => null,
            'meal_3' => null,
            'meal_4' => null,
            'meal_5' => null,
            'meal_6' => null,
        ],
        'day_2' => [
            'meal_1' => null,
            'meal_2' => null,
            'meal_3' => null,
            'meal_4' => null,
            'meal_5' => null,
            'meal_6' => null,
        ],
        'day_3' => [
            'meal_1' => null,
            'meal_2' => null,
            'meal_3' => null,
            'meal_4' => null,
            'meal_5' => null,
            'meal_6' => null,
        ],
        'day_4' => [
            'meal_1' => null,
            'meal_2' => null,
            'meal_3' => null,
            'meal_4' => null,
            'meal_5' => null,
            'meal_6' => null,
        ],
        'day_5' => [
            'meal_1' => null,
            'meal_2' => null,
            'meal_3' => null,
            'meal_4' => null,
            'meal_5' => null,
            'meal_6' => null,
        ],
        'day_6' => [
            'meal_1' => null,
            'meal_2' => null,
            'meal_3' => null,
            'meal_4' => null,
            'meal_5' => null,
            'meal_6' => null,
        ],
        'day_7' => [
            'meal_1' => null,
            'meal_2' => null,
            'meal_3' => null,
            'meal_4' => null,
            'meal_5' => null,
            'meal_6' => null,
        ],
    ],
    'main_servings' => [
        'day_1' => [
            'meal_1' => 1,
            'meal_2' => 1,
            'meal_3' => 1,
            'meal_4' => 1,
            'meal_5' => 1,
            'meal_6' => 1,
        ],
        'day_2' => [
            'meal_1' => 1,
            'meal_2' => 1,
            'meal_3' => 1,
            'meal_4' => 1,
            'meal_5' => 1,
            'meal_6' => 1,
        ],
        'day_3' => [
            'meal_1' => 1,
            'meal_2' => 1,
            'meal_3' => 1,
            'meal_4' => 1,
            'meal_5' => 1,
            'meal_6' => 1,
        ],
        'day_4' => [
            'meal_1' => 1,
            'meal_2' => 1,
            'meal_3' => 1,
            'meal_4' => 1,
            'meal_5' => 1,
            'meal_6' => 1,
        ],
        'day_5' => [
            'meal_1' => 1,
            'meal_2' => 1,
            'meal_3' => 1,
            'meal_4' => 1,
            'meal_5' => 1,
            'meal_6' => 1,
        ],
        'day_6' => [
            'meal_1' => 1,
            'meal_2' => 1,
            'meal_3' => 1,
            'meal_4' => 1,
            'meal_5' => 1,
            'meal_6' => 1,
        ],
        'day_7' => [
            'meal_1' => 1,
            'meal_2' => 1,
            'meal_3' => 1,
            'meal_4' => 1,
            'meal_5' => 1,
            'meal_6' => 1,
        ],
    ],
    'sides_servings' => [
        'day_1' => [
            'meal_1' => null,
            'meal_2' => null,
            'meal_3' => null,
            'meal_4' => null,
            'meal_5' => null,
            'meal_6' => null,
        ],
        'day_2' => [
            'meal_1' => null,
            'meal_2' => null,
            'meal_3' => null,
            'meal_4' => null,
            'meal_5' => null,
            'meal_6' => null,
        ],
        'day_3' => [
            'meal_1' => null,
            'meal_2' => null,
            'meal_3' => null,
            'meal_4' => null,
            'meal_5' => null,
            'meal_6' => null,
        ],
        'day_4' => [
            'meal_1' => null,
            'meal_2' => null,
            'meal_3' => null,
            'meal_4' => null,
            'meal_5' => null,
            'meal_6' => null,
        ],
        'day_5' => [
            'meal_1' => null,
            'meal_2' => null,
            'meal_3' => null,
            'meal_4' => null,
            'meal_5' => null,
            'meal_6' => null,
        ],
        'day_6' => [
            'meal_1' => null,
            'meal_2' => null,
            'meal_3' => null,
            'meal_4' => null,
            'meal_5' => null,
            'meal_6' => null,
        ],
        'day_7' => [
            'meal_1' => null,
            'meal_2' => null,
            'meal_3' => null,
            'meal_4' => null,
            'meal_5' => null,
            'meal_6' => null,
        ],
    ],
    'main_racion' => [
        'day_1' => [
            'meal_1' => 1,
            'meal_2' => 1,
            'meal_3' => 1,
            'meal_4' => 1,
            'meal_5' => 1,
            'meal_6' => 1,
        ],
        'day_2' => [
            'meal_1' => 1,
            'meal_2' => 1,
            'meal_3' => 1,
            'meal_4' => 1,
            'meal_5' => 1,
            'meal_6' => 1,
        ],
        'day_3' => [
            'meal_1' => 1,
            'meal_2' => 1,
            'meal_3' => 1,
            'meal_4' => 1,
            'meal_5' => 1,
            'meal_6' => 1,
        ],
        'day_4' => [
            'meal_1' => 1,
            'meal_2' => 1,
            'meal_3' => 1,
            'meal_4' => 1,
            'meal_5' => 1,
            'meal_6' => 1,
        ],
        'day_5' => [
            'meal_1' => 1,
            'meal_2' => 1,
            'meal_3' => 1,
            'meal_4' => 1,
            'meal_5' => 1,
            'meal_6' => 1,
        ],
        'day_6' => [
            'meal_1' => 1,
            'meal_2' => 1,
            'meal_3' => 1,
            'meal_4' => 1,
            'meal_5' => 1,
            'meal_6' => 1,
        ],
        'day_7' => [
            'meal_1' => 1,
            'meal_2' => 1,
            'meal_3' => 1,
            'meal_4' => 1,
            'meal_5' => 1,
            'meal_6' => 1,
        ],
    ],
    'sides_racion' => [
        'day_1' => [
            'meal_1' => 1,
            'meal_2' => 1,
            'meal_3' => 1,
            'meal_4' => 1,
            'meal_5' => 1,
            'meal_6' => 1,
        ],
        'day_2' => [
            'meal_1' => 1,
            'meal_2' => 1,
            'meal_3' => 1,
            'meal_4' => 1,
            'meal_5' => 1,
            'meal_6' => 1,
        ],
        'day_3' => [
            'meal_1' => 1,
            'meal_2' => 1,
            'meal_3' => 1,
            'meal_4' => 1,
            'meal_5' => 1,
            'meal_6' => 1,
        ],
        'day_4' => [
            'meal_1' => 1,
            'meal_2' => 1,
            'meal_3' => 1,
            'meal_4' => 1,
            'meal_5' => 1,
            'meal_6' => 1,
        ],
        'day_5' => [
            'meal_1' => 1,
            'meal_2' => 1,
            'meal_3' => 1,
            'meal_4' => 1,
            'meal_5' => 1,
            'meal_6' => 1,
        ],
        'day_6' => [
            'meal_1' => 1,
            'meal_2' => 1,
            'meal_3' => 1,
            'meal_4' => 1,
            'meal_5' => 1,
            'meal_6' => 1,
        ],
        'day_7' => [
            'meal_1' => 1,
            'meal_2' => 1,
            'meal_3' => 1,
            'meal_4' => 1,
            'meal_5' => 1,
            'meal_6' => 1,
        ],
    ],
    'labels' => [
        'days' => [
            'day_1' => 'Lunes',
            'day_2' => 'Martes',
            'day_3' => 'Miércoles',
            'day_4' => 'Jueves',
            'day_5' => 'Viernes',
            'day_6' => 'Sábado',
            'day_7' => 'Domingo',
        ],
        'meals' => [
            'meal_1' => 'Desayuno',
            'meal_2' => 'Lunch',
            'meal_3' => 'Comida',
            'meal_4' => 'Snack',
            'meal_5' => 'Cena',
            'meal_6' => 'Otros',
        ],
    ],
    'nutritients' => [
        1003 => 
        [
            'orden' => 5,
            'nombre' => 'Proteína',
            'porcentaje' => 0,
            'color' => '#3afe72',
            'cantidad' => 0,
            'unidad_medida' => 'g',
            'mostrar' => 1,
            'id' => 96,
        ],
        1004 => 
        [
            'orden' => 6,
            'nombre' => 'Grasa total',
            'porcentaje' => 0,
            'color' => '#e79ccd',
            'cantidad' => 0,
            'unidad_medida' => 'g',
            'mostrar' => 1,
            'id' => 97,
        ],
        1005 => 
        [
            'orden' => 2,
            'nombre' => 'Carbohidratos',
            'porcentaje' => 0,
            'color' => '#b279eb',
            'cantidad' => 0,
            'unidad_medida' => 'g',
            'mostrar' => 1,
            'id' => 99,
        ],
        1008 =>
        [
            'orden' => 1,
            'nombre' => 'Calorías',
            'porcentaje' => 0,
            'color' => '#40deb4',
            'cantidad' => 0,
            'unidad_medida' => 'kcal',
            'mostrar' => 1,
            'id' => 94,
        ],
        1079 => 
        [
            'orden' => 3,
            'nombre' => 'Fibra',
            'porcentaje' => 0,
            'color' => '#622817',
            'cantidad' => 0,
            'unidad_medida' => 'g',
            'mostrar' => 1,
            'id' => 213,
        ],
        1087 => 
        [
            'orden' => 10,
            'nombre' => 'Calcio',
            'porcentaje' => 0,
            'color' => '#2ed973',
            'cantidad' => 0,
            'unidad_medida' => 'mg',
            'mostrar' => 1,
            'id' => 102,
        ],
        1089 => 
        [
            'orden' => 11,
            'nombre' => 'Hierro',
            'porcentaje' => 0,
            'color' => '#3ae41f',
            'cantidad' => 0,
            'unidad_medida' => 'mg',
            'mostrar' => 1,
            'id' => 103,
        ],
        1090 => 
        [
            'orden' => 12,
            'nombre' => 'Magnesio',
            'porcentaje' => 0,
            'color' => '#67b394',
            'cantidad' => 0,
            'unidad_medida' => 'mg',
            'mostrar' => 1,
            'id' => 104,
        ],
        1091 => 
        [
            'orden' => 13,
            'nombre' => 'Fósforo',
            'porcentaje' => 0,
            'color' => '#ea6ed4',
            'cantidad' => 0,
            'unidad_medida' => 'mg',
            'mostrar' => 1,
            'id' => 105,
        ],
        1092 => 
        [
            'orden' => 14,
            'nombre' => 'Potasio',
            'porcentaje' => 0,
            'color' => '#d21cf5',
            'cantidad' => 0,
            'unidad_medida' => 'mg',
            'mostrar' => 1,
            'id' => 106,
        ],
        1093 => 
        [
            'orden' => 15,
            'nombre' => 'Sodio',
            'porcentaje' => 0,
            'color' => '#592226',
            'cantidad' => 0,
            'unidad_medida' => 'mg',
            'mostrar' => 1,
            'id' => 107,
        ],
        1095 => 
        [
            'orden' => 16,
            'nombre' => 'Zinc',
            'porcentaje' => 0,
            'color' => '#e00fae',
            'cantidad' => 0,
            'unidad_medida' => 'mg',
            'mostrar' => 1,
            'id' => 108,
        ],
        1103 => 
        [
            'orden' => 18,
            'nombre' => 'Selenio',
            'porcentaje' => 0,
            'color' => '#1aac6b',
            'cantidad' => 0,
            'unidad_medida' => 'µg',
            'mostrar' => 1,
            'id' => 111,
        ],
        1106 => 
        [
            'orden' => 19,
            'nombre' => 'Vitamina A',
            'porcentaje' => 0,
            'color' => '#b52a7b',
            'cantidad' => 0,
            'unidad_medida' => 'µg',
            'mostrar' => 1,
            'id' => 124,
        ],
        1109 => 
        [
            'orden' => 27,
            'nombre' => 'Vitamina E',
            'porcentaje' => 0,
            'color' => '#5ac307',
            'cantidad' => 0,
            'unidad_medida' => 'mg',
            'mostrar' => 1,
            'id' => 129,
        ],
        1110 => 
        [
            'orden' => 26,
            'nombre' => 'Vitamina D',
            'porcentaje' => 0,
            'color' => '#a78c46',
            'cantidad' => 0,
            'unidad_medida' => 'IU',
            'mostrar' => 1,
            'id' => 135,
        ],
        1162 => 
        [
            'orden' => 25,
            'nombre' => 'Vitamina C',
            'porcentaje' => 0,
            'color' => '#3b1aba',
            'cantidad' => 0,
            'unidad_medida' => 'mg',
            'mostrar' => 1,
            'id' => 223,
        ],
        1165 => 
        [
            'orden' => 20,
            'nombre' => 'Vit B1 Tiamina',
            'porcentaje' => 0,
            'color' => '#4b0252',
            'cantidad' => 0,
            'unidad_medida' => 'mg',
            'mostrar' => 1,
            'id' => 113,
        ],
        1166 => 
        [
            'orden' => 21,
            'nombre' => 'Vit B2 Riboflavina',
            'porcentaje' => 0,
            'color' => '#313ee6',
            'cantidad' => 0,
            'unidad_medida' => 'mg',
            'mostrar' => 1,
            'id' => 114,
        ],
        1167 => 
        [
            'orden' => 22,
            'nombre' => 'Vit B3 Niacina',
            'porcentaje' => 0,
            'color' => '#f9c12d',
            'cantidad' => 0,
            'unidad_medida' => 'mg',
            'mostrar' => 1,
            'id' => 115,
        ],
        1175 =>
        [
            'orden' => 23,
            'nombre' => 'Vitamina B6',
            'porcentaje' => 0,
            'color' => '#dac774',
            'cantidad' => 0,
            'unidad_medida' => 'mg',
            'mostrar' => 1,
            'id' => 117,
        ],
        1177 => 
        [
            'orden' => 29,
            'nombre' => 'Folato',
            'porcentaje' => 0,
            'color' => '#af13a6',
            'cantidad' => 0,
            'unidad_medida' => 'µg',
            'mostrar' => 1,
            'id' => 118,
        ],
        1178 => 
        [
            'orden' => 24,
            'nombre' => 'Vitamina B12',
            'porcentaje' => 0,
            'color' => '#a6917a',
            'cantidad' => 0,
            'unidad_medida' => 'µg',
            'mostrar' => 1,
            'id' => 123,
        ],
        1180 => 
        [
            'orden' => 30,
            'nombre' => 'Choline',
            'porcentaje' => 0,
            'color' => '#f183eb',
            'cantidad' => 0,
            'unidad_medida' => 'mg',
            'mostrar' => 1,
            'id' => 121,
        ],
        1185 => 
        [
            'orden' => 28,
            'nombre' => 'Vitamina K',
            'porcentaje' => 0,
            'color' => '#e464d4',
            'cantidad' => 0,
            'unidad_medida' => 'µg',
            'mostrar' => 1,
            'id' => 138,
        ],
        1253 => 
        [
            'orden' => 9,
            'nombre' => 'Colesterol',
            'porcentaje' => 0,
            'color' => '#b7e8f4',
            'cantidad' => 0,
            'unidad_medida' => 'mg',
            'mostrar' => 1,
            'id' => 180,
        ],
        1258 => 
        [
            'orden' => 7,
            'nombre' => 'Saturada',
            'porcentaje' => 0,
            'color' => '#f1e54c',
            'cantidad' => 0,
            'unidad_medida' => 'g',
            'mostrar' => 1,
            'id' => 140,
        ],
        1292 => 
        [
            'orden' => 8,
            'nombre' => 'Monoinsaturada',
            'porcentaje' => 0,
            'color' => '#40967c',
            'cantidad' => 0,
            'unidad_medida' => 'g',
            'mostrar' => 1,
            'id' => 151,
        ],
        1293 => 
        [
            'orden' => 8,
            'nombre' => 'Poliinsaturada',
            'porcentaje' => 0,
            'color' => '#d31433',
            'cantidad' => 0,
            'unidad_medida' => 'g',
            'mostrar' => 1,
            'id' => 159,
        ],
        2000 => 
        [
            'orden' => 4,
            'nombre' => 'Azúcar',
            'porcentaje' => 0,
            'color' => '#d16618',
            'cantidad' => 0,
            'unidad_medida' => 'g',
            'mostrar' => 1,
            'id' => 100,
        ],
    ],
];